#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Gate.Resource", IsApplication=true)]

namespace Gate
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05005e
			public const int accessLevelSpinner = 2131034206;
			
			// aapt resource value: 0x7f050004
			public const int accessNameField = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int accessNameView = 2131034115;
			
			// aapt resource value: 0x7f05005d
			public const int accessView = 2131034205;
			
			// aapt resource value: 0x7f050057
			public const int cancelAccessButton = 2131034199;
			
			// aapt resource value: 0x7f050061
			public const int cancelCardButton = 2131034209;
			
			// aapt resource value: 0x7f05005b
			public const int cardField = 2131034203;
			
			// aapt resource value: 0x7f05005a
			public const int cardNameField = 2131034202;
			
			// aapt resource value: 0x7f050059
			public const int cardNameView = 2131034201;
			
			// aapt resource value: 0x7f05005c
			public const int cardNumberField = 2131034204;
			
			// aapt resource value: 0x7f050060
			public const int dateAdded = 2131034208;
			
			// aapt resource value: 0x7f050055
			public const int dateEnd = 2131034197;
			
			// aapt resource value: 0x7f050054
			public const int dateEndView = 2131034196;
			
			// aapt resource value: 0x7f050052
			public const int dateStart = 2131034194;
			
			// aapt resource value: 0x7f050051
			public const int dateStartView = 2131034193;
			
			// aapt resource value: 0x7f050007
			public const int dayHeader1 = 2131034119;
			
			// aapt resource value: 0x7f050028
			public const int dayHeader2 = 2131034152;
			
			// aapt resource value: 0x7f05006a
			public const int deleteAccessLevels = 2131034218;
			
			// aapt resource value: 0x7f050068
			public const int deleteAll = 2131034216;
			
			// aapt resource value: 0x7f050069
			public const int deleteCards = 2131034217;
			
			// aapt resource value: 0x7f05006b
			public const int deleteTransactions = 2131034219;
			
			// aapt resource value: 0x7f050058
			public const int doneAccessButton = 2131034200;
			
			// aapt resource value: 0x7f050062
			public const int doneCardButton = 2131034210;
			
			// aapt resource value: 0x7f05004e
			public const int enableView = 2131034190;
			
			// aapt resource value: 0x7f050021
			public const int endTimeFriday = 2131034145;
			
			// aapt resource value: 0x7f050009
			public const int endTimeHeader = 2131034121;
			
			// aapt resource value: 0x7f050011
			public const int endTimeMonday = 2131034129;
			
			// aapt resource value: 0x7f050025
			public const int endTimeSaturday = 2131034149;
			
			// aapt resource value: 0x7f05000d
			public const int endTimeSunday = 2131034125;
			
			// aapt resource value: 0x7f05001d
			public const int endTimeThursday = 2131034141;
			
			// aapt resource value: 0x7f050015
			public const int endTimeTuesday = 2131034133;
			
			// aapt resource value: 0x7f050019
			public const int endTimeWednesday = 2131034137;
			
			// aapt resource value: 0x7f050067
			public const int frameLayout1 = 2131034215;
			
			// aapt resource value: 0x7f05001f
			public const int fridayView1 = 2131034143;
			
			// aapt resource value: 0x7f050040
			public const int fridayView2 = 2131034176;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout2 = 2131034114;
			
			// aapt resource value: 0x7f050047
			public const int linearLayout3 = 2131034183;
			
			// aapt resource value: 0x7f05004d
			public const int linearLayout4 = 2131034189;
			
			// aapt resource value: 0x7f050056
			public const int linearLayout5 = 2131034198;
			
			// aapt resource value: 0x7f05004a
			public const int linearLayout6 = 2131034186;
			
			// aapt resource value: 0x7f050050
			public const int linearLayout7 = 2131034192;
			
			// aapt resource value: 0x7f050053
			public const int linearLayout8 = 2131034195;
			
			// aapt resource value: 0x7f050063
			public const int listView = 2131034211;
			
			// aapt resource value: 0x7f050065
			public const int listView1 = 2131034213;
			
			// aapt resource value: 0x7f050066
			public const int listView2 = 2131034214;
			
			// aapt resource value: 0x7f05000f
			public const int mondayView1 = 2131034127;
			
			// aapt resource value: 0x7f050030
			public const int mondayView2 = 2131034160;
			
			// aapt resource value: 0x7f050049
			public const int numberOfUsesField = 2131034185;
			
			// aapt resource value: 0x7f050041
			public const int r1Fri = 2131034177;
			
			// aapt resource value: 0x7f050031
			public const int r1Mon = 2131034161;
			
			// aapt resource value: 0x7f050045
			public const int r1Sat = 2131034181;
			
			// aapt resource value: 0x7f05002d
			public const int r1Sun = 2131034157;
			
			// aapt resource value: 0x7f05003d
			public const int r1Thurs = 2131034173;
			
			// aapt resource value: 0x7f050035
			public const int r1Tues = 2131034165;
			
			// aapt resource value: 0x7f050039
			public const int r1Wed = 2131034169;
			
			// aapt resource value: 0x7f050042
			public const int r2Fri = 2131034178;
			
			// aapt resource value: 0x7f050032
			public const int r2Mon = 2131034162;
			
			// aapt resource value: 0x7f050046
			public const int r2Sat = 2131034182;
			
			// aapt resource value: 0x7f05002e
			public const int r2Sun = 2131034158;
			
			// aapt resource value: 0x7f05003e
			public const int r2Thurs = 2131034174;
			
			// aapt resource value: 0x7f050036
			public const int r2Tues = 2131034166;
			
			// aapt resource value: 0x7f05003a
			public const int r2Wed = 2131034170;
			
			// aapt resource value: 0x7f050023
			public const int saturdayView1 = 2131034147;
			
			// aapt resource value: 0x7f050044
			public const int saturdayView2 = 2131034180;
			
			// aapt resource value: 0x7f050000
			public const int scrollView1 = 2131034112;
			
			// aapt resource value: 0x7f050020
			public const int startTimeFriday = 2131034144;
			
			// aapt resource value: 0x7f050008
			public const int startTimeHeader = 2131034120;
			
			// aapt resource value: 0x7f050010
			public const int startTimeMonday = 2131034128;
			
			// aapt resource value: 0x7f050024
			public const int startTimeSaturday = 2131034148;
			
			// aapt resource value: 0x7f05000c
			public const int startTimeSunday = 2131034124;
			
			// aapt resource value: 0x7f05001c
			public const int startTimeThursday = 2131034140;
			
			// aapt resource value: 0x7f050014
			public const int startTimeTuesday = 2131034132;
			
			// aapt resource value: 0x7f050018
			public const int startTimeWednesday = 2131034136;
			
			// aapt resource value: 0x7f05000b
			public const int sundayView1 = 2131034123;
			
			// aapt resource value: 0x7f05002c
			public const int sundayView2 = 2131034156;
			
			// aapt resource value: 0x7f050005
			public const int tableLayout1 = 2131034117;
			
			// aapt resource value: 0x7f050026
			public const int tableLayout2 = 2131034150;
			
			// aapt resource value: 0x7f050006
			public const int tableRow1 = 2131034118;
			
			// aapt resource value: 0x7f05002b
			public const int tableRow11 = 2131034155;
			
			// aapt resource value: 0x7f05002f
			public const int tableRow12 = 2131034159;
			
			// aapt resource value: 0x7f050033
			public const int tableRow13 = 2131034163;
			
			// aapt resource value: 0x7f050037
			public const int tableRow14 = 2131034167;
			
			// aapt resource value: 0x7f050043
			public const int tableRow15 = 2131034179;
			
			// aapt resource value: 0x7f05003b
			public const int tableRow16 = 2131034171;
			
			// aapt resource value: 0x7f05003f
			public const int tableRow17 = 2131034175;
			
			// aapt resource value: 0x7f05000a
			public const int tableRow2 = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int tableRow3 = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int tableRow4 = 2131034130;
			
			// aapt resource value: 0x7f05001a
			public const int tableRow5 = 2131034138;
			
			// aapt resource value: 0x7f050016
			public const int tableRow6 = 2131034134;
			
			// aapt resource value: 0x7f05001e
			public const int tableRow7 = 2131034142;
			
			// aapt resource value: 0x7f050022
			public const int tableRow8 = 2131034146;
			
			// aapt resource value: 0x7f050027
			public const int tableRow9 = 2131034151;
			
			// aapt resource value: 0x7f05005f
			public const int textView1 = 2131034207;
			
			// aapt resource value: 0x7f050064
			public const int textView2 = 2131034212;
			
			// aapt resource value: 0x7f050029
			public const int textView21 = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int textView22 = 2131034154;
			
			// aapt resource value: 0x7f05004b
			public const int textView23 = 2131034187;
			
			// aapt resource value: 0x7f05006e
			public const int textView3 = 2131034222;
			
			// aapt resource value: 0x7f050070
			public const int textView4 = 2131034224;
			
			// aapt resource value: 0x7f05001b
			public const int thursdayView1 = 2131034139;
			
			// aapt resource value: 0x7f05003c
			public const int thursdayView2 = 2131034172;
			
			// aapt resource value: 0x7f05006c
			public const int transactionCard = 2131034220;
			
			// aapt resource value: 0x7f050071
			public const int transactionError = 2131034225;
			
			// aapt resource value: 0x7f05006f
			public const int transactionReader = 2131034223;
			
			// aapt resource value: 0x7f05006d
			public const int transactionTime = 2131034221;
			
			// aapt resource value: 0x7f050013
			public const int tuesdayView1 = 2131034131;
			
			// aapt resource value: 0x7f050034
			public const int tuesdayView2 = 2131034164;
			
			// aapt resource value: 0x7f05004f
			public const int useDateRange = 2131034191;
			
			// aapt resource value: 0x7f05004c
			public const int usePassBack = 2131034188;
			
			// aapt resource value: 0x7f050048
			public const int usesView = 2131034184;
			
			// aapt resource value: 0x7f050017
			public const int wednesdayView1 = 2131034135;
			
			// aapt resource value: 0x7f050038
			public const int wednesdayView2 = 2131034168;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddAccessLevel = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddCard = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListDisplay = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListDisplay2 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Settings = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Transaction = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int AccessLevel = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040014
			public const int Cancel = 2130968596;
			
			// aapt resource value: 0x7f040002
			public const int CardNumber = 2130968578;
			
			// aapt resource value: 0x7f040022
			public const int DateAdded = 2130968610;
			
			// aapt resource value: 0x7f04001c
			public const int DateEnd = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int DateStart = 2130968603;
			
			// aapt resource value: 0x7f040009
			public const int Day = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int DefaultEndTime = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int DefaultStartTime = 2130968583;
			
			// aapt resource value: 0x7f04001a
			public const int DeleteAccessLevels = 2130968602;
			
			// aapt resource value: 0x7f040018
			public const int DeleteAll = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int DeleteCards = 2130968601;
			
			// aapt resource value: 0x7f04001e
			public const int DeleteTransactions = 2130968606;
			
			// aapt resource value: 0x7f040015
			public const int Done = 2130968597;
			
			// aapt resource value: 0x7f040013
			public const int EnableDateRange = 2130968595;
			
			// aapt resource value: 0x7f040011
			public const int EnablePassBack = 2130968593;
			
			// aapt resource value: 0x7f040006
			public const int EndTime = 2130968582;
			
			// aapt resource value: 0x7f040020
			public const int ErrorCode = 2130968608;
			
			// aapt resource value: 0x7f04000e
			public const int Friday = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int Monday = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int Name = 2130968577;
			
			// aapt resource value: 0x7f040012
			public const int NumberOfUses = 2130968594;
			
			// aapt resource value: 0x7f040021
			public const int ReaderNumber = 2130968609;
			
			// aapt resource value: 0x7f04001d
			public const int Reconnect = 2130968605;
			
			// aapt resource value: 0x7f04000f
			public const int Saturday = 2130968591;
			
			// aapt resource value: 0x7f040005
			public const int StartTime = 2130968581;
			
			// aapt resource value: 0x7f040010
			public const int Sunday = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int Thursday = 2130968589;
			
			// aapt resource value: 0x7f04001f
			public const int Time = 2130968607;
			
			// aapt resource value: 0x7f04000b
			public const int Tuesday = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int Wednesday = 2130968588;
			
			// aapt resource value: 0x7f040004
			public const int Week = 2130968580;
			
			// aapt resource value: 0x7f040016
			public const int one = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int two = 2130968599;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
