//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Gate.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ICardService", Namespace="http://tempuri.org/")]
    public partial class CardService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransactionListOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTransactionSQLOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAllTransactionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOneCardSQLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCardListOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAllCardsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOneAccessSQLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccessLevelListOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAccessOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAllAccessAndCardsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyValuesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CardService() {
            this.Url = "http://192.168.2.236:8000/DMTSolutions/CardReader";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloCompletedEventHandler HelloCompleted;
        
        /// <remarks/>
        public event GetTransactionListCompletedEventHandler GetTransactionListCompleted;
        
        /// <remarks/>
        public event UpdateTransactionSQLCompletedEventHandler UpdateTransactionSQLCompleted;
        
        /// <remarks/>
        public event DeleteTransactionCompletedEventHandler DeleteTransactionCompleted;
        
        /// <remarks/>
        public event DeleteAllTransactionsCompletedEventHandler DeleteAllTransactionsCompleted;
        
        /// <remarks/>
        public event AddOneCardSQLCompletedEventHandler AddOneCardSQLCompleted;
        
        /// <remarks/>
        public event GetCardListCompletedEventHandler GetCardListCompleted;
        
        /// <remarks/>
        public event DeleteCardCompletedEventHandler DeleteCardCompleted;
        
        /// <remarks/>
        public event DeleteAllCardsCompletedEventHandler DeleteAllCardsCompleted;
        
        /// <remarks/>
        public event AddOneAccessSQLCompletedEventHandler AddOneAccessSQLCompleted;
        
        /// <remarks/>
        public event GetAccessLevelListCompletedEventHandler GetAccessLevelListCompleted;
        
        /// <remarks/>
        public event DeleteAccessCompletedEventHandler DeleteAccessCompleted;
        
        /// <remarks/>
        public event DeleteAllAccessAndCardsCompletedEventHandler DeleteAllAccessAndCardsCompleted;
        
        /// <remarks/>
        public event ModifyValuesCompletedEventHandler ModifyValuesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Hello", RequestNamespace="http://dmtserv.CardServices", ResponseNamespace="http://dmtserv.CardServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Hello() {
            object[] results = this.Invoke("Hello", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloAsync() {
            this.HelloAsync(null);
        }
        
        /// <remarks/>
        public void HelloAsync(object userState) {
            if ((this.HelloOperationCompleted == null)) {
                this.HelloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloOperationCompleted);
            }
            this.InvokeAsync("Hello", new object[0], this.HelloOperationCompleted, userState);
        }
        
        private void OnHelloOperationCompleted(object arg) {
            if ((this.HelloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloCompleted(this, new HelloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GetTransactionList", RequestNamespace="http://dmtserv.CardServices", ResponseNamespace="http://dmtserv.CardServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Transaction[] GetTransactionList() {
            object[] results = this.Invoke("GetTransactionList", new object[0]);
            return ((Transaction[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTransactionListAsync() {
            this.GetTransactionListAsync(null);
        }
        
        /// <remarks/>
        public void GetTransactionListAsync(object userState) {
            if ((this.GetTransactionListOperationCompleted == null)) {
                this.GetTransactionListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransactionListOperationCompleted);
            }
            this.InvokeAsync("GetTransactionList", new object[0], this.GetTransactionListOperationCompleted, userState);
        }
        
        private void OnGetTransactionListOperationCompleted(object arg) {
            if ((this.GetTransactionListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransactionListCompleted(this, new GetTransactionListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("UpdateTransactionSQL", RequestNamespace="http://dmtserv.CardServices", ResponseNamespace="http://dmtserv.CardServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateTransactionSQL([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] Transaction[] newTransactions, out bool UpdateTransactionSQLResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool UpdateTransactionSQLResultSpecified) {
            object[] results = this.Invoke("UpdateTransactionSQL", new object[] {
                        newTransactions});
            UpdateTransactionSQLResult = ((bool)(results[0]));
            UpdateTransactionSQLResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void UpdateTransactionSQLAsync(Transaction[] newTransactions) {
            this.UpdateTransactionSQLAsync(newTransactions, null);
        }
        
        /// <remarks/>
        public void UpdateTransactionSQLAsync(Transaction[] newTransactions, object userState) {
            if ((this.UpdateTransactionSQLOperationCompleted == null)) {
                this.UpdateTransactionSQLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTransactionSQLOperationCompleted);
            }
            this.InvokeAsync("UpdateTransactionSQL", new object[] {
                        newTransactions}, this.UpdateTransactionSQLOperationCompleted, userState);
        }
        
        private void OnUpdateTransactionSQLOperationCompleted(object arg) {
            if ((this.UpdateTransactionSQLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTransactionSQLCompleted(this, new UpdateTransactionSQLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DeleteTransaction", RequestNamespace="http://dmtserv.CardServices", ResponseNamespace="http://dmtserv.CardServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteTransaction(System.DateTime tTime, [System.Xml.Serialization.XmlIgnoreAttribute()] bool tTimeSpecified, out bool DeleteTransactionResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool DeleteTransactionResultSpecified) {
            object[] results = this.Invoke("DeleteTransaction", new object[] {
                        tTime,
                        tTimeSpecified});
            DeleteTransactionResult = ((bool)(results[0]));
            DeleteTransactionResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void DeleteTransactionAsync(System.DateTime tTime, bool tTimeSpecified) {
            this.DeleteTransactionAsync(tTime, tTimeSpecified, null);
        }
        
        /// <remarks/>
        public void DeleteTransactionAsync(System.DateTime tTime, bool tTimeSpecified, object userState) {
            if ((this.DeleteTransactionOperationCompleted == null)) {
                this.DeleteTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteTransactionOperationCompleted);
            }
            this.InvokeAsync("DeleteTransaction", new object[] {
                        tTime,
                        tTimeSpecified}, this.DeleteTransactionOperationCompleted, userState);
        }
        
        private void OnDeleteTransactionOperationCompleted(object arg) {
            if ((this.DeleteTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteTransactionCompleted(this, new DeleteTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DeleteAllTransactions", RequestNamespace="http://dmtserv.CardServices", ResponseNamespace="http://dmtserv.CardServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteAllTransactions(out bool DeleteAllTransactionsResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool DeleteAllTransactionsResultSpecified) {
            object[] results = this.Invoke("DeleteAllTransactions", new object[0]);
            DeleteAllTransactionsResult = ((bool)(results[0]));
            DeleteAllTransactionsResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void DeleteAllTransactionsAsync() {
            this.DeleteAllTransactionsAsync(null);
        }
        
        /// <remarks/>
        public void DeleteAllTransactionsAsync(object userState) {
            if ((this.DeleteAllTransactionsOperationCompleted == null)) {
                this.DeleteAllTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAllTransactionsOperationCompleted);
            }
            this.InvokeAsync("DeleteAllTransactions", new object[0], this.DeleteAllTransactionsOperationCompleted, userState);
        }
        
        private void OnDeleteAllTransactionsOperationCompleted(object arg) {
            if ((this.DeleteAllTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAllTransactionsCompleted(this, new DeleteAllTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("UpdateOneCardSQL", RequestNamespace="http://dmtserv.CardServices", ResponseNamespace="http://dmtserv.CardServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddOneCardSQL([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Card card, out bool AddOneCardSQLResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool AddOneCardSQLResultSpecified) {
            object[] results = this.Invoke("AddOneCardSQL", new object[] {
                        card});
            AddOneCardSQLResult = ((bool)(results[0]));
            AddOneCardSQLResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void AddOneCardSQLAsync(Card card) {
            this.AddOneCardSQLAsync(card, null);
        }
        
        /// <remarks/>
        public void AddOneCardSQLAsync(Card card, object userState) {
            if ((this.AddOneCardSQLOperationCompleted == null)) {
                this.AddOneCardSQLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOneCardSQLOperationCompleted);
            }
            this.InvokeAsync("AddOneCardSQL", new object[] {
                        card}, this.AddOneCardSQLOperationCompleted, userState);
        }
        
        private void OnAddOneCardSQLOperationCompleted(object arg) {
            if ((this.AddOneCardSQLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOneCardSQLCompleted(this, new AddOneCardSQLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GetCardList", RequestNamespace="http://dmtserv.CardServices", ResponseNamespace="http://dmtserv.CardServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Card[] GetCardList() {
            object[] results = this.Invoke("GetCardList", new object[0]);
            return ((Card[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCardListAsync() {
            this.GetCardListAsync(null);
        }
        
        /// <remarks/>
        public void GetCardListAsync(object userState) {
            if ((this.GetCardListOperationCompleted == null)) {
                this.GetCardListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCardListOperationCompleted);
            }
            this.InvokeAsync("GetCardList", new object[0], this.GetCardListOperationCompleted, userState);
        }
        
        private void OnGetCardListOperationCompleted(object arg) {
            if ((this.GetCardListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCardListCompleted(this, new GetCardListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DeleteCard", RequestNamespace="http://dmtserv.CardServices", ResponseNamespace="http://dmtserv.CardServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteCard([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cName, out bool DeleteCardResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool DeleteCardResultSpecified) {
            object[] results = this.Invoke("DeleteCard", new object[] {
                        cName});
            DeleteCardResult = ((bool)(results[0]));
            DeleteCardResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void DeleteCardAsync(string cName) {
            this.DeleteCardAsync(cName, null);
        }
        
        /// <remarks/>
        public void DeleteCardAsync(string cName, object userState) {
            if ((this.DeleteCardOperationCompleted == null)) {
                this.DeleteCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCardOperationCompleted);
            }
            this.InvokeAsync("DeleteCard", new object[] {
                        cName}, this.DeleteCardOperationCompleted, userState);
        }
        
        private void OnDeleteCardOperationCompleted(object arg) {
            if ((this.DeleteCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCardCompleted(this, new DeleteCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DeleteAllCards", RequestNamespace="http://dmtserv.CardServices", ResponseNamespace="http://dmtserv.CardServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteAllCards(out bool DeleteAllCardsResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool DeleteAllCardsResultSpecified) {
            object[] results = this.Invoke("DeleteAllCards", new object[0]);
            DeleteAllCardsResult = ((bool)(results[0]));
            DeleteAllCardsResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void DeleteAllCardsAsync() {
            this.DeleteAllCardsAsync(null);
        }
        
        /// <remarks/>
        public void DeleteAllCardsAsync(object userState) {
            if ((this.DeleteAllCardsOperationCompleted == null)) {
                this.DeleteAllCardsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAllCardsOperationCompleted);
            }
            this.InvokeAsync("DeleteAllCards", new object[0], this.DeleteAllCardsOperationCompleted, userState);
        }
        
        private void OnDeleteAllCardsOperationCompleted(object arg) {
            if ((this.DeleteAllCardsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAllCardsCompleted(this, new DeleteAllCardsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("UpdateAccessSQL", RequestNamespace="http://dmtserv.CardServices", ResponseNamespace="http://dmtserv.CardServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddOneAccessSQL([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AccessLevel access, out bool AddOneAccessSQLResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool AddOneAccessSQLResultSpecified) {
            object[] results = this.Invoke("AddOneAccessSQL", new object[] {
                        access});
            AddOneAccessSQLResult = ((bool)(results[0]));
            AddOneAccessSQLResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void AddOneAccessSQLAsync(AccessLevel access) {
            this.AddOneAccessSQLAsync(access, null);
        }
        
        /// <remarks/>
        public void AddOneAccessSQLAsync(AccessLevel access, object userState) {
            if ((this.AddOneAccessSQLOperationCompleted == null)) {
                this.AddOneAccessSQLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOneAccessSQLOperationCompleted);
            }
            this.InvokeAsync("AddOneAccessSQL", new object[] {
                        access}, this.AddOneAccessSQLOperationCompleted, userState);
        }
        
        private void OnAddOneAccessSQLOperationCompleted(object arg) {
            if ((this.AddOneAccessSQLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOneAccessSQLCompleted(this, new AddOneAccessSQLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GetAccessList", RequestNamespace="http://dmtserv.CardServices", ResponseNamespace="http://dmtserv.CardServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public AccessLevel[] GetAccessLevelList() {
            object[] results = this.Invoke("GetAccessLevelList", new object[0]);
            return ((AccessLevel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAccessLevelListAsync() {
            this.GetAccessLevelListAsync(null);
        }
        
        /// <remarks/>
        public void GetAccessLevelListAsync(object userState) {
            if ((this.GetAccessLevelListOperationCompleted == null)) {
                this.GetAccessLevelListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccessLevelListOperationCompleted);
            }
            this.InvokeAsync("GetAccessLevelList", new object[0], this.GetAccessLevelListOperationCompleted, userState);
        }
        
        private void OnGetAccessLevelListOperationCompleted(object arg) {
            if ((this.GetAccessLevelListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccessLevelListCompleted(this, new GetAccessLevelListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DeleteAccess", RequestNamespace="http://dmtserv.CardServices", ResponseNamespace="http://dmtserv.CardServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteAccess([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string aName, out bool DeleteAccessResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool DeleteAccessResultSpecified) {
            object[] results = this.Invoke("DeleteAccess", new object[] {
                        aName});
            DeleteAccessResult = ((bool)(results[0]));
            DeleteAccessResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void DeleteAccessAsync(string aName) {
            this.DeleteAccessAsync(aName, null);
        }
        
        /// <remarks/>
        public void DeleteAccessAsync(string aName, object userState) {
            if ((this.DeleteAccessOperationCompleted == null)) {
                this.DeleteAccessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAccessOperationCompleted);
            }
            this.InvokeAsync("DeleteAccess", new object[] {
                        aName}, this.DeleteAccessOperationCompleted, userState);
        }
        
        private void OnDeleteAccessOperationCompleted(object arg) {
            if ((this.DeleteAccessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAccessCompleted(this, new DeleteAccessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DeleteAllAccessAndCards", RequestNamespace="http://dmtserv.CardServices", ResponseNamespace="http://dmtserv.CardServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteAllAccessAndCards(out bool DeleteAllAccessAndCardsResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool DeleteAllAccessAndCardsResultSpecified) {
            object[] results = this.Invoke("DeleteAllAccessAndCards", new object[0]);
            DeleteAllAccessAndCardsResult = ((bool)(results[0]));
            DeleteAllAccessAndCardsResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void DeleteAllAccessAndCardsAsync() {
            this.DeleteAllAccessAndCardsAsync(null);
        }
        
        /// <remarks/>
        public void DeleteAllAccessAndCardsAsync(object userState) {
            if ((this.DeleteAllAccessAndCardsOperationCompleted == null)) {
                this.DeleteAllAccessAndCardsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAllAccessAndCardsOperationCompleted);
            }
            this.InvokeAsync("DeleteAllAccessAndCards", new object[0], this.DeleteAllAccessAndCardsOperationCompleted, userState);
        }
        
        private void OnDeleteAllAccessAndCardsOperationCompleted(object arg) {
            if ((this.DeleteAllAccessAndCardsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAllAccessAndCardsCompleted(this, new DeleteAllAccessAndCardsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ModifyValues", RequestNamespace="http://dmtserv.CardServices", ResponseNamespace="http://dmtserv.CardServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModifyValues([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string table, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string column, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] object oldv, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] object newv, out bool ModifyValuesResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ModifyValuesResultSpecified) {
            object[] results = this.Invoke("ModifyValues", new object[] {
                        table,
                        column,
                        oldv,
                        newv});
            ModifyValuesResult = ((bool)(results[0]));
            ModifyValuesResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void ModifyValuesAsync(string table, string column, object oldv, object newv) {
            this.ModifyValuesAsync(table, column, oldv, newv, null);
        }
        
        /// <remarks/>
        public void ModifyValuesAsync(string table, string column, object oldv, object newv, object userState) {
            if ((this.ModifyValuesOperationCompleted == null)) {
                this.ModifyValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyValuesOperationCompleted);
            }
            this.InvokeAsync("ModifyValues", new object[] {
                        table,
                        column,
                        oldv,
                        newv}, this.ModifyValuesOperationCompleted, userState);
        }
        
        private void OnModifyValuesOperationCompleted(object arg) {
            if ((this.ModifyValuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyValuesCompleted(this, new ModifyValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://dmtserv.CardServices")]
    public partial class Transaction
    {

        private int cardCodeField;

        private string cardHolderField;

        private System.DateTime dateTimeField;

        private int errorNumberField;

        private int readerNumberField;

        public Transaction() { }

        public Transaction(int readerNumber, int cardCode, DateTime dateTime, int errorCode, string cardHolder)
        {
            this.readerNumber = readerNumber;
            this.cardCode = cardCode;
            this.dateTime = dateTime;
            this.errorNumber = errorCode;
            this.cardHolder = cardHolder;
        }

        /// <remarks/>
        public int cardCode
        {
            get
            {
                return this.cardCodeField;
            }
            set
            {
                this.cardCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string cardHolder
        {
            get
            {
                return this.cardHolderField;
            }
            set
            {
                this.cardHolderField = value;
            }
        }

        /// <remarks/>
        public System.DateTime dateTime
        {
            get
            {
                return this.dateTimeField;
            }
            set
            {
                this.dateTimeField = value;
            }
        }

        /// <remarks/>
        public int errorNumber
        {
            get
            {
                return this.errorNumberField;
            }
            set
            {
                this.errorNumberField = value;
            }
        }

        /// <remarks/>
        public int readerNumber
        {
            get
            {
                return this.readerNumberField;
            }
            set
            {
                this.readerNumberField = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://dmtserv.CardServices")]
    public partial class AccessLevel
    {

        private System.DateTime dateEndField;

        private System.DateTime dateStartField;

        private string nameField;

        private int numberOfUsesField;

        private bool useDateRangeField;

        private bool usePassBackField;

        private string[] weekReader1AccessField;

        private string[] weekReader2AccessField;

        private System.DateTime[] weekTimeEndField;

        private System.DateTime[] weekTimeStartField;

        public AccessLevel() { }

        public AccessLevel(string name, DateTime[] weekTimeStart, DateTime[] weekTimeEnd, string[] weekReader1Access, string[] weekReader2Access,
    bool usePassBack, int numberOfUses, bool useDateRange, DateTime dateStart, DateTime dateEnd)
        {
            this.name = name;
            this.weekTimeStart = weekTimeStart;
            this.weekTimeEnd = weekTimeEnd;
            this.weekReader1Access = weekReader1Access;
            this.weekReader2Access = weekReader2Access;
            this.usePassBack = usePassBack;
            this.numberOfUses = numberOfUses;
            this.useDateRange = useDateRange;
            this.dateStart = dateStart;
            this.dateEnd = dateEnd;
        }

        /// <remarks/>
        public System.DateTime dateEnd
        {
            get
            {
                return this.dateEndField;
            }
            set
            {
                this.dateEndField = value;
            }
        }


        /// <remarks/>
        public System.DateTime dateStart
        {
            get
            {
                return this.dateStartField;
            }
            set
            {
                this.dateStartField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public int numberOfUses
        {
            get
            {
                return this.numberOfUsesField;
            }
            set
            {
                this.numberOfUsesField = value;
            }
        }

        /// <remarks/>
        public bool useDateRange
        {
            get
            {
                return this.useDateRangeField;
            }
            set
            {
                this.useDateRangeField = value;
            }
        }

        /// <remarks/>
        public bool usePassBack
        {
            get
            {
                return this.usePassBackField;
            }
            set
            {
                this.usePassBackField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] weekReader1Access
        {
            get
            {
                return this.weekReader1AccessField;
            }
            set
            {
                this.weekReader1AccessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] weekReader2Access
        {
            get
            {
                return this.weekReader2AccessField;
            }
            set
            {
                this.weekReader2AccessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable = false)]
        public System.DateTime[] weekTimeEnd
        {
            get
            {
                return this.weekTimeEndField;
            }
            set
            {
                this.weekTimeEndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable = false)]
        public System.DateTime[] weekTimeStart
        {
            get
            {
                return this.weekTimeStartField;
            }
            set
            {
                this.weekTimeStartField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://dmtserv.CardServices")]
    public partial class Card
    {

        private string accessLevelField;

        private int cardCodeField;

        private System.DateTime dateAddedField;

        private string nameField;

        public Card() { }

        public Card(string name, int cardCode, string accessLevel, DateTime dateAdded)
        {
            this.name = name;
            this.cardCode = cardCode;
            this.accessLevel = accessLevel;
            this.dateAdded = dateAdded;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string accessLevel
        {
            get
            {
                return this.accessLevelField;
            }
            set
            {
                this.accessLevelField = value;
            }
        }

        /// <remarks/>
        public int cardCode
        {
            get
            {
                return this.cardCodeField;
            }
            set
            {
                this.cardCodeField = value;
            }
        }

        /// <remarks/>
        public System.DateTime dateAdded
        {
            get
            {
                return this.dateAddedField;
            }
            set
            {
                this.dateAddedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HelloCompletedEventHandler(object sender, HelloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTransactionListCompletedEventHandler(object sender, GetTransactionListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransactionListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransactionListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transaction[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transaction[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateTransactionSQLCompletedEventHandler(object sender, UpdateTransactionSQLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTransactionSQLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTransactionSQLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool UpdateTransactionSQLResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool UpdateTransactionSQLResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteTransactionCompletedEventHandler(object sender, DeleteTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool DeleteTransactionResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool DeleteTransactionResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteAllTransactionsCompletedEventHandler(object sender, DeleteAllTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteAllTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteAllTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool DeleteAllTransactionsResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool DeleteAllTransactionsResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AddOneCardSQLCompletedEventHandler(object sender, AddOneCardSQLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOneCardSQLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOneCardSQLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool AddOneCardSQLResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool AddOneCardSQLResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCardListCompletedEventHandler(object sender, GetCardListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCardListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCardListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Card[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Card[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteCardCompletedEventHandler(object sender, DeleteCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool DeleteCardResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool DeleteCardResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteAllCardsCompletedEventHandler(object sender, DeleteAllCardsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteAllCardsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteAllCardsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool DeleteAllCardsResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool DeleteAllCardsResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AddOneAccessSQLCompletedEventHandler(object sender, AddOneAccessSQLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOneAccessSQLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOneAccessSQLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool AddOneAccessSQLResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool AddOneAccessSQLResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAccessLevelListCompletedEventHandler(object sender, GetAccessLevelListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccessLevelListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccessLevelListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccessLevel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccessLevel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteAccessCompletedEventHandler(object sender, DeleteAccessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteAccessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteAccessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool DeleteAccessResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool DeleteAccessResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteAllAccessAndCardsCompletedEventHandler(object sender, DeleteAllAccessAndCardsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteAllAccessAndCardsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteAllAccessAndCardsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool DeleteAllAccessAndCardsResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool DeleteAllAccessAndCardsResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ModifyValuesCompletedEventHandler(object sender, ModifyValuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifyValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool ModifyValuesResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool ModifyValuesResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591